
plugins {
    id 'java-library'
    id 'idea'
    id 'net.neoforged.gradle.userdev' version '7.0.142'
    id 'multiloader-loader'
}


tasks.withType(JavaExec) {
    enableAssertions = true
}

def at = file('src/main/resources/META-INF/accesstransformer.cfg')
if (at.exists()) {
    minecraft.accessTransformers.file at
}

archivesBaseName = "${mod_name}-${minecraft_version}-NEOFORGE"
if (System.getenv().RELEASE_MODE == null) {
    archivesBaseName += '-SNAPSHOT'
}

    runs {
        configureEach {
            modSource project.sourceSets.main
        }
        client {
            systemProperty 'neoforge.enabledGameTestNamespaces', project.mod_id
        }
        server {
            systemProperty 'neoforge.enabledGameTestNamespaces', project.mod_id
            programArgument '--nogui'
        }

        gameTestServer {
            systemProperty 'neoforge.enabledGameTestNamespaces', project.mod_id
        }

        data {
            programArguments.addAll '--mod', project.mod_id, '--all', '--output', file('src/generated/resources/').getAbsolutePath(), '--existing', file('src/main/resources/').getAbsolutePath()
        }
    }
dependencies {
    implementation "net.neoforged:neoforge:${neoforge_version}"
    //Jei
    compileOnly("mezz.jei:jei-${minecraft_version}-neoforge-api:${jei_version}")
    // at runtime, use the full JEI jar for NeoForge
    runtimeOnly("mezz.jei:jei-${minecraft_version}-neoforge:${jei_version}")
}


idea {
    module {
        downloadSources = true
        downloadJavadoc = true
    }
}


