
plugins {
    id 'java-library'
    id 'idea'
    id 'net.neoforged.gradle.userdev' version '7.0.133'
}


tasks.withType(JavaExec) {
    enableAssertions = true
}

def at = file('src/main/resources/META-INF/accesstransformer.cfg')
if (at.exists()) {
    minecraft.accessTransformers.file at
}

archivesBaseName = "${mod_name}-${minecraft_version}-NEOFORGE"
if (System.getenv().RELEASE_MODE == null) {
    archivesBaseName += '-SNAPSHOT'
}


    runs {
        configureEach {
            modSource project.sourceSets.main
        }
        client {
            systemProperty 'neoforge.enabledGameTestNamespaces', project.mod_id
        }
        server {
            systemProperty 'neoforge.enabledGameTestNamespaces', project.mod_id
            programArgument '--nogui'
        }

        gameTestServer {
            systemProperty 'neoforge.enabledGameTestNamespaces', project.mod_id
        }

        data {
            programArguments.addAll '--mod', project.mod_id, '--all', '--output', file('src/generated/resources/').getAbsolutePath(), '--existing', file('src/main/resources/').getAbsolutePath()
        }
    }




sourceSets.main.resources { srcDir 'src/generated/resources' }

dependencies {

    implementation "net.neoforged:neoforge:${neo_version}"
    annotationProcessor 'org.spongepowered:mixin:0.8.5:processor'
    compileOnly project(":Common")
    compileOnly("mezz.jei:jei-${minecraft_version}-common-api:${jei_version}")
    testCompileOnly("mezz.jei:jei-${minecraft_version}-common-api:${jei_version}")
    // at runtime, use the full JEI jar for Forge
    runtimeOnly("mezz.jei:jei-${minecraft_version}-neoforge:${jei_version}")
}

processResources {

    from project(":Common").sourceSets.main.resources

    inputs.properties(
            "mod_id": mod_id,
            "version": project.version,
            "mod_name": mod_name,
            "mod_description": mod_description,
            "forge_version": neo_version,
            minimum_neoforge_version: minimum_neoforge_version,
            "mod_author": mod_author,
            "minecraft_version": minecraft_version
    )


    filesMatching("neoforge.mods.toml") {
        expand(
                "mod_id": mod_id,
                "version": project.version,
                "mod_name": mod_name,
                "mod_description": mod_description,
                "mod_author": mod_author,
                "neogorge_version": neo_version,
                minimum_neoforge_version: minimum_neoforge_version,
                "minecraft_version": minecraft_version
        )
    }

    filesMatching('pack.mcmeta') {
        expand("mod_name": mod_name)
    }
}


jar {
    manifest {
        attributes([
                "Specification-Title"     : mod_name,
                "Specification-Vendor"    : mod_author,
                "Specification-Version"   : "1", // We are version 1 of ourselves
                "Implementation-Title"    : mod_name,
                "Implementation-Version"  : version,
                "Implementation-Vendor"   : mod_author,
                "Implementation-Timestamp": new Date().format("yyyy-MM-dd'T'HH:mm:ssZ")
        ])
    }
}

idea {
    module {
        downloadSources = true
        downloadJavadoc = true
    }
}


