on:
   workflow_dispatch:
jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout sources
      uses: actions/checkout@v4
    - name: Setup env variables
      run: echo RELEASE_MODE=PRODUCTION >> $GITHUB_ENV
    - uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '21'
        cache: 'gradle'
        cache-dependency-path: | # optional
          *.gradle*
    - name: Setup Gradle
      uses: gradle/gradle-build-action@v3
    - name: Build with Gradle
      run: ./gradlew build --no-daemon --max-workers 1
    - uses: actions/upload-artifact@v4
      with:
        path: | 
          Fabric/build/libs
          Forge/build/libs     
    - uses: Kir-Antipov/mc-publish@v3.3
      with:

        changelog-file: CHANGELOG.*
        name: ""

        modrinth-id: 5qWx4yJx
        modrinth-token: ${{ secrets.MODRINTH_TOKEN }}

        #curseforge-id: 697859
        #curseforge-token: ${{ secrets.CURSEFORGE_TOKEN }}
        files: |
          Fabric/build/libs/!(*-@(dev|sources|javadoc)).jar
          Forge/build/libs/!(*-@(dev|sources|javadoc)).jar

        dependencies: |
            jei(optional){modrinth:u6dRKJwZ}{curseforge:238222}
