on:
   workflow_dispatch:
jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    permissions:
     id-token: write
     attestations: write
    steps:
    - name: Checkout sources
      uses: actions/checkout@v4
    - name: Setup env variables
      run: echo RELEASE_MODE=PRODUCTION >> $GITHUB_ENV
    - uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '21'
        cache: 'gradle'
    - name: Setup Gradle
      uses: gradle/gradle-build-action@v3
    - name: Build with Gradle
      run: ./gradlew build --no-daemon --max-workers 1
    - uses: actions/upload-artifact@v4
      with:
        path: | 
          Fabric/build/libs
          NeoForge/build/libs
    - name: Attest build provenance
    - uses: actions/attest-build-provenance@v1
      with:
          subject-path: | 
            NeoForge/build/libs/!(*-@(dev|sources|javadoc)).jar
            Fabric/build/libs/!(*-@(dev|sources|javadoc)).jar

    #Forge upload
    - uses: Kir-Antipov/mc-publish@v3.3
      with:
        changelog-file: CHANGELOG.*
        modrinth-id: xe4saW9d
        modrinth-token: ${{ secrets.MODRINTH_TOKEN }}

        curseforge-id: 697859
        curseforge-token: ${{ secrets.CURSEFORGE_TOKEN }}
        files: |
          NeoForge/build/libs/!(*-@(dev|sources|javadoc)).jar

        dependencies: |
            jei(optional){modrinth:u6dRKJwZ}{curseforge:238222}

    #Fabric upload
    - uses: Kir-Antipov/mc-publish@v3.3
      with:

        changelog-file: CHANGELOG.*
        modrinth-id: xe4saW9d
        modrinth-token: ${{ secrets.MODRINTH_TOKEN }}

        curseforge-id: 697859
        curseforge-token: ${{ secrets.CURSEFORGE_TOKEN }}
        files: |
          NeoForge/build/libs/!(*-@(dev|sources|javadoc)).jar

        dependencies: |
          jei(optional){modrinth:u6dRKJwZ}{curseforge:238222}
